### ISSUE TITLE
`npm run build` fails on npm v2

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/spectacle-boilerplate#6] opened 2016-01-13 01:51 UTC
Works fine on npmv3, but:

```sh
$ npm install
$ npm run build
```

On npmv 2 yields:

```
$ npm run build

> spectacle-boilerplate@1.0.0 build /Users/rroemer/scm/fmd/builder-decks
> webpack --config webpack.config.dev.js

Hash: a868f206d3f2f91fbe56
Version: webpack 1.12.11
Time: 4215ms
   [0] multi main 40 bytes {0} [built]
    + 387 hidden modules

ERROR in ./~/spectacle/~/history/lib/createBrowserHistory.js
Module not found: Error: Cannot resolve module 'invariant' in /Users/rroemer/scm/fmd/builder-decks/node_modules/spectacle/node_modules/history/lib
 @ ./~/spectacle/~/history/lib/createBrowserHistory.js 9:17-37

ERROR in ./~/spectacle/~/history/lib/createHashHistory.js
Module not found: Error: Cannot resolve module 'invariant' in /Users/rroemer/scm/fmd/builder-decks/node_modules/spectacle/node_modules/history/lib
 @ ./~/spectacle/~/history/lib/createHashHistory.js 13:17-37

ERROR in ./~/spectacle/~/history/lib/createHashHistory.js
Module not found: Error: Cannot resolve module 'warning' in /Users/rroemer/scm/fmd/builder-decks/node_modules/spectacle/node_modules/history/lib
 @ ./~/spectacle/~/history/lib/createHashHistory.js 9:15-33

ERROR in ./~/spectacle/~/history/lib/DOMStateStorage.js
Module not found: Error: Cannot resolve module 'warning' in /Users/rroemer/scm/fmd/builder-decks/node_modules/spectacle/node_modules/history/lib
 @ ./~/spectacle/~/history/lib/DOMStateStorage.js 10:15-33

ERROR in ./~/spectacle/~/history/lib/createDOMHistory.js
Module not found: Error: Cannot resolve module 'invariant' in /Users/rroemer/scm/fmd/builder-decks/node_modules/spectacle/node_modules/history/lib
 @ ./~/spectacle/~/history/lib/createDOMHistory.js 9:17-37

ERROR in ./~/spectacle/~/history/lib/createHistory.js
Module not found: Error: Cannot resolve module 'deep-equal' in /Users/rroemer/scm/fmd/builder-decks/node_modules/spectacle/node_modules/history/lib
 @ ./~/spectacle/~/history/lib/createHistory.js 9:17-38

ERROR in ./~/spectacle/~/history/lib/runTransitionHook.js
Module not found: Error: Cannot resolve module 'warning' in /Users/rroemer/scm/fmd/builder-decks/node_modules/spectacle/node_modules/history/lib
 @ ./~/spectacle/~/history/lib/runTransitionHook.js 7:15-33

ERROR in ./~/spectacle/~/history/lib/deprecate.js
Module not found: Error: Cannot resolve module 'warning' in /Users/rroemer/scm/fmd/builder-decks/node_modules/spectacle/node_modules/history/lib
 @ ./~/spectacle/~/history/lib/deprecate.js 7:15-33

ERROR in ./~/spectacle/~/history/lib/parsePath.js
Module not found: Error: Cannot resolve module 'warning' in /Users/rroemer/scm/fmd/builder-decks/node_modules/spectacle/node_modules/history/lib
 @ ./~/spectacle/~/history/lib/parsePath.js 7:15-33
```

**Comment by kenwheeler** [comment] 2016-01-14 14:45
closing as a dupe of #4 , fixing in the core lib

**Closed by kenwheeler** 2016-01-14 14:45 UTC
Labels: bug
